---
version: "3"
services:
  app:
    image: "node:13"
    volumes:
      - "node_modules:/app/node_modules"
      - ".:/app"
      - "${APP_DEMO_DIR}:/app/var"
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      STEAM_API_KEY: "${STEAM_API_KEY}"
    command: npx nodemon
volumes:
  node_modules:
    driver: local
